export enum InsuranceType {
  SEGURO_FACULTATIVO_IMSS = 'SEGURO_FACULTATIVO_IMSS',
  SEGURO_GASTOS_MEDICOS_MAYORES = 'SEGURO_GASTOS_MEDICOS_MAYORES',
  SEGURO_ACCIDENTES_PERSONALES_ESCOLARES = 'SEGURO_ACCIDENTES_PERSONALES_ESCOLARES',
  SEGURO_SALUD_FAMILIA = 'SEGURO_SALUD_FAMILIA',
}
